{% set name = "dbt-athena-community" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 50494c5a0a651898c007831e370a1a7780fe1af080dbb696b3b176c6ac69b98e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - boto3 >=1.34,<2.dev0
    - boto3-stubs >=1.34,<2.dev0
    - dbt-core >=1.7.0,<1.8.dev0
    - mmh3 >=4.0.1,<4.2.0
    - pyathena >=2.25,<4.0
    - pydantic >=1.10,<3.0
    - tenacity >=8.2,<9.dev0

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-athena/dbt-athena
  summary: The athena adapter plugin for dbt (data build tool)
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - briandconnelly
